package game;

import game.movement.AngledAcceleration;
import game.character.Boat;
import game.character.Character;


public class ControlPanel extends javax.swing.JPanel
{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private double accelerationScale=0.1;
    private double maxVelocityScale=3.0;
    
    private double frictionScale=0.05;
    private double brakeScale=5;
    
    private double angAccelerationScale=0.01;
    private double maxAngularVelocityScale=0.1;
    private double angularFrictionScale=0.001;
    
    private final int SLIDER_MAXIMUM=1000;
    
    
    
    
    /**
     * Creates new form ControlPanel
     */
    public ControlPanel()
    {
	initComponents();
	
    }
    
    private void scaleAcceleration()
    {
	this.accelerationScale = Double.valueOf(this.jTxtScaleAcceleration.getText());
	
    }
    
    private void scaleMaxVelocity()
    {
	this.maxVelocityScale = Double.valueOf(this.jTxtScaleMaximumVelocity.getText());
	
    }
    
    private void scaleFriction()
    {
	this.frictionScale = Double.valueOf(this.jTxtFrictionScale.getText());
	
    }
    
    
    private void scaleBraking()
    {
	this.brakeScale = Double.valueOf(this.jTxtBrakingScale.getText());
	
    }
    
    private void scaleAngularFriction()
    {
	this.angularFrictionScale = Double.valueOf(this.jTxtAngularFriction.getText());
    }
    
    
    private void scaleAngularAcceleration()
    {
	this.angAccelerationScale = Double.valueOf(this.jTxtAngAccelerationScale.getText());
	
    }
    
    private void scaleMaxAngularVelocity()
    {
	this.maxAngularVelocityScale = Double.valueOf(this.jTxtMaxAngularVelocity.getText());
	
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPnlControls = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSldScaleMaximumVelocity = new javax.swing.JSlider();
        jLblMaximumVelocity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtScaleMaximumVelocity = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblBrakeScale = new javax.swing.JLabel();
        sldBrake = new javax.swing.JSlider();
        jTxtBrakingScale = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLblVelocity = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLblAngle = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLblAngularVelocity = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLblX = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLblY = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSldAcceleration = new javax.swing.JSlider();
        jLblAcceleration = new javax.swing.JLabel();
        jTxtScaleAcceleration = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblFrictionScale = new javax.swing.JLabel();
        sldFriction = new javax.swing.JSlider();
        jTxtFrictionScale = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jSldAngularAcceleration = new javax.swing.JSlider();
        jLblAngularAcceleration = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtAngAccelerationScale = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jSldMaximumAngularVelocity = new javax.swing.JSlider();
        jLblMaximumAngularVelocity = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtMaxAngularVelocity = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jSldAngularFriction = new javax.swing.JSlider();
        jLblAngularFriction = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtAngularFriction = new javax.swing.JTextField();

        jPnlControls.setBackground(new java.awt.Color(204, 204, 204));
        jPnlControls.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSldScaleMaximumVelocity.setMajorTickSpacing(5);
        jSldScaleMaximumVelocity.setMaximum(1000);
        jSldScaleMaximumVelocity.setMaximum(SLIDER_MAXIMUM);
        jSldScaleMaximumVelocity.setMinorTickSpacing(1);
        jSldScaleMaximumVelocity.setValue(500);
        jSldScaleMaximumVelocity.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSldScaleMaximumVelocityStateChanged(evt);
            }
        });

        jLblMaximumVelocity.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblMaximumVelocity.setText("x");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel4.setText("Max Velocity");

        jTxtScaleMaximumVelocity.setText("100");
        jTxtScaleMaximumVelocity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtScaleMaximumVelocityActionPerformed(evt);
            }
        });
        jTxtScaleMaximumVelocity.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtScaleMaximumVelocityFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSldScaleMaximumVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(jLblMaximumVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtScaleMaximumVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtScaleMaximumVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblMaximumVelocity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSldScaleMaximumVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel5.setText("Braking pix/frame per  frame");

        lblBrakeScale.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblBrakeScale.setText("x");

        sldBrake.setMajorTickSpacing(5);
        sldBrake.setMaximum(1000);
        sldBrake.setMaximum(SLIDER_MAXIMUM);
        sldBrake.setMinorTickSpacing(1);
        sldBrake.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                sldBrakeStateChanged(evt);
            }
        });

        jTxtBrakingScale.setText("100");
        jTxtBrakingScale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtBrakingScaleActionPerformed(evt);
            }
        });
        jTxtBrakingScale.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtBrakingScaleFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBrakeScale, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jTxtBrakingScale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sldBrake, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblBrakeScale)
                    .addComponent(jTxtBrakingScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldBrake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel9.setText("Velocity");

        jLblVelocity.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblVelocity.setText("x");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel11.setText("Angle");

        jLblAngle.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblAngle.setText("x");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel13.setText("Angular Velocity");

        jLblAngularVelocity.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblAngularVelocity.setText("x");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblAngle, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblAngularVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblVelocity)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLblAngularVelocity))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLblAngle)))
        );

        jLblX.setBackground(new java.awt.Color(204, 255, 153));
        jLblX.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblX.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel6.setText("X Position");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel7.setText("Y Position");

        jLblY.setBackground(new java.awt.Color(204, 255, 153));
        jLblY.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblY.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblX)
                    .addComponent(jLblY))
                .addGap(149, 149, 149))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLblX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblY)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel1.setText("Accel pixels/frame per frame");

        jSldAcceleration.setMajorTickSpacing(5);
        jSldAcceleration.setMaximum(1000);
        jSldAcceleration.setMaximum(SLIDER_MAXIMUM);
        jSldAcceleration.setMinorTickSpacing(1);
        jSldAcceleration.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSldAccelerationStateChanged(evt);
            }
        });

        jLblAcceleration.setBackground(new java.awt.Color(204, 255, 153));
        jLblAcceleration.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblAcceleration.setText("0");

        jTxtScaleAcceleration.setText("100");
        jTxtScaleAcceleration.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtScaleAccelerationActionPerformed(evt);
            }
        });
        jTxtScaleAcceleration.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtScaleAccelerationFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSldAcceleration, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblAcceleration, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtScaleAcceleration, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtScaleAcceleration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAcceleration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSldAcceleration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel8.setText("Velocity Friction");

        lblFrictionScale.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblFrictionScale.setText("x");

        sldFriction.setMajorTickSpacing(5);
        sldFriction.setMaximum(1000);
        sldFriction.setMaximum(SLIDER_MAXIMUM);
        sldFriction.setMinorTickSpacing(1);
        sldFriction.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                sldFrictionStateChanged(evt);
            }
        });

        jTxtFrictionScale.setText("100");
        jTxtFrictionScale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtFrictionScaleActionPerformed(evt);
            }
        });
        jTxtFrictionScale.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtFrictionScaleFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldFriction, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21)
                        .addComponent(lblFrictionScale, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFrictionScale, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblFrictionScale))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTxtFrictionScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldFriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSldAngularAcceleration.setMajorTickSpacing(5);
        jSldAngularAcceleration.setMaximum(1000);
        jSldAngularAcceleration.setMaximum(SLIDER_MAXIMUM);
        jSldAngularAcceleration.setMinorTickSpacing(1);
        jSldAngularAcceleration.setValue(500);
        jSldAngularAcceleration.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSldAngularAccelerationStateChanged(evt);
            }
        });

        jLblAngularAcceleration.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblAngularAcceleration.setText("x");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel10.setText("Angular acceleration Rad / frame");

        jTxtAngAccelerationScale.setText("100");
        jTxtAngAccelerationScale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtAngAccelerationScaleActionPerformed(evt);
            }
        });
        jTxtAngAccelerationScale.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtAngAccelerationScaleFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSldAngularAcceleration, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblAngularAcceleration, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAngAccelerationScale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLblAngularAcceleration))
                    .addComponent(jTxtAngAccelerationScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSldAngularAcceleration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSldMaximumAngularVelocity.setMajorTickSpacing(5);
        jSldMaximumAngularVelocity.setMaximum(1000);
        jSldMaximumAngularVelocity.setMaximum(SLIDER_MAXIMUM);
        jSldMaximumAngularVelocity.setMinorTickSpacing(1);
        jSldMaximumAngularVelocity.setValue(500);
        jSldMaximumAngularVelocity.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSldMaximumAngularVelocityStateChanged(evt);
            }
        });

        jLblMaximumAngularVelocity.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblMaximumAngularVelocity.setText("x");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel12.setText("Angular Max Velocity");

        jTxtMaxAngularVelocity.setText("100");
        jTxtMaxAngularVelocity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtMaxAngularVelocityActionPerformed(evt);
            }
        });
        jTxtMaxAngularVelocity.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtMaxAngularVelocityFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSldMaximumAngularVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(46, 46, 46)
                        .addComponent(jLblMaximumAngularVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMaxAngularVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTxtMaxAngularVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblMaximumAngularVelocity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSldMaximumAngularVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jSldAngularFriction.setMajorTickSpacing(5);
        jSldAngularFriction.setMaximum(1000);
        jSldAngularFriction.setMinorTickSpacing(1);
        jSldAngularFriction.setValue(500);
        jSldAngularFriction.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSldAngularFrictionStateChanged(evt);
            }
        });

        jLblAngularFriction.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblAngularFriction.setText("x");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 9));
        jLabel14.setText("Angular Friction");

        jTxtAngularFriction.setText("100");
        jTxtAngularFriction.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtAngularFrictionActionPerformed(evt);
            }
        });
        jTxtAngularFriction.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtAngularFrictionFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSldAngularFriction, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(46, 46, 46)
                        .addComponent(jLblAngularFriction, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAngularFriction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtAngularFriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAngularFriction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSldAngularFriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlControlsLayout = new javax.swing.GroupLayout(jPnlControls);
        jPnlControls.setLayout(jPnlControlsLayout);
        jPnlControlsLayout.setHorizontalGroup(
            jPnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlControlsLayout.createSequentialGroup()
                .addGroup(jPnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlControlsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlControlsLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnlControlsLayout.setVerticalGroup(
            jPnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTxtAngularFrictionFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtAngularFrictionFocusLost
    {//GEN-HEADEREND:event_jTxtAngularFrictionFocusLost
	scaleAngularFriction();
    }//GEN-LAST:event_jTxtAngularFrictionFocusLost
    
    private void jTxtAngularFrictionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtAngularFrictionActionPerformed
    {//GEN-HEADEREND:event_jTxtAngularFrictionActionPerformed
	scaleAngularFriction();
    }//GEN-LAST:event_jTxtAngularFrictionActionPerformed
    
    private void jSldAngularFrictionStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSldAngularFrictionStateChanged
    {//GEN-HEADEREND:event_jSldAngularFrictionStateChanged
	sldAngularFrictionChange();
    }//GEN-LAST:event_jSldAngularFrictionStateChanged
    
    private void jTxtMaxAngularVelocityFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtMaxAngularVelocityFocusLost
    {//GEN-HEADEREND:event_jTxtMaxAngularVelocityFocusLost
	this.scaleMaxAngularVelocity();
    }//GEN-LAST:event_jTxtMaxAngularVelocityFocusLost
    
    private void jTxtMaxAngularVelocityActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtMaxAngularVelocityActionPerformed
    {//GEN-HEADEREND:event_jTxtMaxAngularVelocityActionPerformed
	this.scaleMaxAngularVelocity();
    }//GEN-LAST:event_jTxtMaxAngularVelocityActionPerformed
    
    private void jTxtBrakingScaleFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtBrakingScaleFocusLost
    {//GEN-HEADEREND:event_jTxtBrakingScaleFocusLost
	this.scaleBraking();
    }//GEN-LAST:event_jTxtBrakingScaleFocusLost
    
    private void jTxtAngAccelerationScaleFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtAngAccelerationScaleFocusLost
    {//GEN-HEADEREND:event_jTxtAngAccelerationScaleFocusLost
	this.scaleAngularAcceleration();
    }//GEN-LAST:event_jTxtAngAccelerationScaleFocusLost
    
    private void jTxtAngAccelerationScaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtAngAccelerationScaleActionPerformed
    {//GEN-HEADEREND:event_jTxtAngAccelerationScaleActionPerformed
	this.scaleAngularAcceleration();
    }//GEN-LAST:event_jTxtAngAccelerationScaleActionPerformed
    
    private void jTxtScaleMaximumVelocityFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtScaleMaximumVelocityFocusLost
    {//GEN-HEADEREND:event_jTxtScaleMaximumVelocityFocusLost
	this.scaleMaxVelocity();
    }//GEN-LAST:event_jTxtScaleMaximumVelocityFocusLost
    
    private void jTxtScaleMaximumVelocityActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtScaleMaximumVelocityActionPerformed
    {//GEN-HEADEREND:event_jTxtScaleMaximumVelocityActionPerformed
	this.scaleMaxVelocity();
    }//GEN-LAST:event_jTxtScaleMaximumVelocityActionPerformed
    
    private void jTxtScaleAccelerationFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtScaleAccelerationFocusLost
    {//GEN-HEADEREND:event_jTxtScaleAccelerationFocusLost
	this.scaleAcceleration();
    }//GEN-LAST:event_jTxtScaleAccelerationFocusLost
    
    private void jTxtScaleAccelerationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtScaleAccelerationActionPerformed
    {//GEN-HEADEREND:event_jTxtScaleAccelerationActionPerformed
	this.scaleAcceleration();
    }//GEN-LAST:event_jTxtScaleAccelerationActionPerformed
    
    private void jTxtBrakingScaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtBrakingScaleActionPerformed
    {//GEN-HEADEREND:event_jTxtBrakingScaleActionPerformed
	this.scaleBraking();
    }//GEN-LAST:event_jTxtBrakingScaleActionPerformed
    
    private void jSldMaximumAngularVelocityStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSldMaximumAngularVelocityStateChanged
    {//GEN-HEADEREND:event_jSldMaximumAngularVelocityStateChanged
	
	this.sldMaximumAngularVelocityChange();
    }//GEN-LAST:event_jSldMaximumAngularVelocityStateChanged
    
    private void jTxtFrictionScaleFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtFrictionScaleFocusLost
    {//GEN-HEADEREND:event_jTxtFrictionScaleFocusLost
	scaleFriction();
    }//GEN-LAST:event_jTxtFrictionScaleFocusLost
    
    private void jTxtFrictionScaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtFrictionScaleActionPerformed
    {//GEN-HEADEREND:event_jTxtFrictionScaleActionPerformed
	scaleFriction();
    }//GEN-LAST:event_jTxtFrictionScaleActionPerformed
    
    private void jSldAngularAccelerationStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSldAngularAccelerationStateChanged
    {//GEN-HEADEREND:event_jSldAngularAccelerationStateChanged
	sldAngularAccelerationChange();
    }//GEN-LAST:event_jSldAngularAccelerationStateChanged
    
    private void sldFrictionStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sldFrictionStateChanged
    {//GEN-HEADEREND:event_sldFrictionStateChanged
	this.sldFrictionChange();
    }//GEN-LAST:event_sldFrictionStateChanged
    
    private void jSldAccelerationStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSldAccelerationStateChanged
    {//GEN-HEADEREND:event_jSldAccelerationStateChanged
	sldAccelerationChange();
    }//GEN-LAST:event_jSldAccelerationStateChanged
    
    private void sldBrakeStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sldBrakeStateChanged
    {//GEN-HEADEREND:event_sldBrakeStateChanged
	this.sldBrakeChange();
    }//GEN-LAST:event_sldBrakeStateChanged
    
    private void jSldScaleMaximumVelocityStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSldScaleMaximumVelocityStateChanged
    {//GEN-HEADEREND:event_jSldScaleMaximumVelocityStateChanged
	this.sldMaximumVelocityChange();
    }//GEN-LAST:event_jSldScaleMaximumVelocityStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblAcceleration;
    private javax.swing.JLabel jLblAngle;
    private javax.swing.JLabel jLblAngularAcceleration;
    private javax.swing.JLabel jLblAngularFriction;
    private javax.swing.JLabel jLblAngularVelocity;
    private javax.swing.JLabel jLblMaximumAngularVelocity;
    private javax.swing.JLabel jLblMaximumVelocity;
    private javax.swing.JLabel jLblVelocity;
    private javax.swing.JLabel jLblX;
    private javax.swing.JLabel jLblY;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnlControls;
    private javax.swing.JSlider jSldAcceleration;
    private javax.swing.JSlider jSldAngularAcceleration;
    private javax.swing.JSlider jSldAngularFriction;
    private javax.swing.JSlider jSldMaximumAngularVelocity;
    private javax.swing.JSlider jSldScaleMaximumVelocity;
    private javax.swing.JTextField jTxtAngAccelerationScale;
    private javax.swing.JTextField jTxtAngularFriction;
    private javax.swing.JTextField jTxtBrakingScale;
    private javax.swing.JTextField jTxtFrictionScale;
    private javax.swing.JTextField jTxtMaxAngularVelocity;
    private javax.swing.JTextField jTxtScaleAcceleration;
    private javax.swing.JTextField jTxtScaleMaximumVelocity;
    private javax.swing.JLabel lblBrakeScale;
    private javax.swing.JLabel lblFrictionScale;
    private javax.swing.JSlider sldBrake;
    private javax.swing.JSlider sldFriction;
    // End of variables declaration//GEN-END:variables
    
    private void sldFrictionChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setFriction((this.sldFriction.getValue()*(this.frictionScale/this.SLIDER_MAXIMUM)));
	
	
    }
    
    private void sldBrakeChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setBrake(this.sldBrake.getValue()*(this.brakeScale/this.SLIDER_MAXIMUM));
	
    }
    
    private void sldAccelerationChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setAcceleration(
		(this.jSldAcceleration.getValue()*(this.accelerationScale/this.SLIDER_MAXIMUM)));
    }
    
    private void sldMaximumVelocityChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setMaxVelocity(
		(this.jSldScaleMaximumVelocity.getValue()*(this.maxVelocityScale/this.SLIDER_MAXIMUM)));
	
    }
    
    
    private void sldAngularAccelerationChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setAngularAcceleration(
		(this.jSldAngularAcceleration.getValue()*this.angAccelerationScale/this.SLIDER_MAXIMUM));
	
    }
    
    
    private void sldMaximumAngularVelocityChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setAngularMaxVelocity(
		(this.jSldMaximumAngularVelocity.getValue()*(this.maxAngularVelocityScale/this.SLIDER_MAXIMUM)));
	
    }
    
    private void sldAngularFrictionChange()
    {
	GameEngine ge = GameEngine.getInstance();
	AngledAcceleration mb = (AngledAcceleration)ge.getCharacters().get("Boat").getMoveBehaviour();
	mb.setAngularFriction(
		(this.jSldAngularFriction.getValue()*(this.angularFrictionScale/this.SLIDER_MAXIMUM)));
    }
    
    public void initializeControlPanel(Character boat)
    {
	
	AngledAcceleration mb = (AngledAcceleration )boat.getMoveBehaviour();
	
	//location
	this.jLblX.setText(String.valueOf((int)boat.getLocation().getX()));
	this.jLblY.setText(String.valueOf((int)boat.getLocation().getY()));
	
	//velocity
	this.jLblVelocity.setText(String.valueOf(mb.getVelocity()));
	
	//angle
	this.jLblAngle.setText(String.valueOf(mb.getAngle()));
	
	//aceleration
	this.jLblAcceleration.setText(String.valueOf(mb.getAcceleration()));
	this.jSldAcceleration.setValue((int)(mb.getAcceleration()
		*(this.SLIDER_MAXIMUM/this.accelerationScale)));
	this.jTxtScaleAcceleration.setText(String.valueOf(this.accelerationScale));
	
	//maximum velocity
	this.jLblMaximumVelocity.setText(String.valueOf(mb.getMaxVelocity()));
	this.jSldScaleMaximumVelocity.setValue((int)(mb.getMaxVelocity()
	*(SLIDER_MAXIMUM/this.maxVelocityScale)));
	this.jTxtScaleMaximumVelocity.setText(String.valueOf(this.maxVelocityScale));
	
	//brake
	this.lblBrakeScale.setText(String.valueOf(mb.getBrake()));
	this.sldBrake.setValue((int)(mb.getBrake()
	*(SLIDER_MAXIMUM/this.brakeScale)));
	this.jTxtBrakingScale.setText(String.valueOf(this.brakeScale));
	
	//friction
	this.lblFrictionScale.setText(String.valueOf(mb.getFriction()));
	this.sldFriction.setValue((int)(mb.getFriction()
	*(SLIDER_MAXIMUM/this.frictionScale)));
	this.jTxtFrictionScale.setText(String.valueOf(this.frictionScale));
	
	//angular acceleration
	this.jLblAngularAcceleration.setText(String.valueOf(mb.getAngularAcceleration()));
	this.jSldAngularAcceleration.setValue((int)(mb.getAngularAcceleration()
	*(SLIDER_MAXIMUM/this.angAccelerationScale)));
	this.jTxtAngAccelerationScale.setText(String.valueOf(this.angAccelerationScale));
	
	//max angular velocity
	this.jLblMaximumAngularVelocity.setText(String.valueOf(mb.getFriction()));
	this.jSldMaximumAngularVelocity.setValue((int)(mb.getAngularMaxVelocity()
	*(SLIDER_MAXIMUM/maxAngularVelocityScale)));
	this.jTxtMaxAngularVelocity.setText(String.valueOf(this.maxAngularVelocityScale));
	
	
	//Angular Friction
	this.jLblAngularFriction.setText(String.valueOf(mb.getAngularFriction()));
	this.jSldAngularFriction.setValue((int)(mb.getAngularFriction()
	*(SLIDER_MAXIMUM/this.angularFrictionScale)));
	this.jTxtAngularFriction.setText(String.valueOf(this.angularFrictionScale));
	
    }
    public void updateControlPanel(Boat boat)
    {
	
	AngledAcceleration mb = (AngledAcceleration )boat.getMoveBehaviour();
	
	//location
	this.jLblX.setText(String.valueOf((int)boat.getLocation().getX()));
	this.jLblY.setText(String.valueOf((int)boat.getLocation().getY()));
	
	//velocity
	this.jLblVelocity.setText(String.valueOf(mb.getVelocity()));
	
	//angle
	this.jLblAngle.setText(String.valueOf(mb.getAngle()));
	
	//angular velocity
	this.jLblAngularVelocity.setText(String.valueOf(mb.getAngularVelocity()));
	//aceleration
	this.jLblAcceleration.setText(String.valueOf(mb.getAcceleration()));
	
	
	//maximum velocity
	this.jLblMaximumVelocity.setText(String.valueOf(mb.getMaxVelocity()));
	
	
	
	//brake
	this.lblBrakeScale.setText(String.valueOf(mb.getBrake()));
	
	
	//friction
	this.lblFrictionScale.setText(String.valueOf(mb.getFriction()));
	
	
	//angular acceleration
	this.jLblAngularAcceleration.setText(String.valueOf(mb.getAngularAcceleration()));
	
	
	//max angular velocity
	this.jLblMaximumAngularVelocity.setText(String.valueOf(mb.getAngularMaxVelocity()));
	
	//Angular Friction
	this.jLblAngularFriction.setText(String.valueOf(mb.getAngularFriction()));
	
	
	
    }
}
